language: php

php:
- 7.1
- 7.2
- 7.3
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_script:
- composer install --no-interaction

after_script:
- php vendor/bin/coveralls -v

script:
- ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml